### ISSUE TITLE
ZF 2.5 compatibility

### ISSUE THREAD

**Issue by personman** [API-Skeletons/zf-doctrine-audit#10]
I'm trying to install this via composer into an app built on Zend Framework 2.5. Composer is throwing the error message that says some versions of zf-doctrine-audit work with earlier versions and others work with later versions of ZF. Is this just an oddity of the way the requirements were set up or is there really no version of this that works with ZF 2.5? Thanks!

**Comment by TomHAnderson** [comment]
Which version of this library are you trying to use?

**Comment by personman** [comment]
I'm open to any version that will work with Zend Framework 2.5. I'm not specifying a version of the audit library in my composer.json. I'm just setting the version as "*", so composer tries to find a version compatible with the rest of my packages.  Here are the errors I see:

`> php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - api-skeletons/zf-doctrine-audit 1.0.1 requires zendframework/zendframework ~2.4,<2.5 -> satisfiable by zendframework/zendframework[2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9] but these conflict with your requirements or minimum-stability.
    - api-skeletons/zf-doctrine-audit 1 requires zendframework/zendframework ~2.4,<2.5 -> satisfiable by zendframework/zendframework[2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9] but these conflict with your requirements or minimum-stability.
    - api-skeletons/zf-doctrine-audit 0.3.0 requires zendframework/zendframework ~2.4,<2.5 -> satisfiable by zendframework/zendframework[2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9] but these conflict with your requirements or minimum-stability.
    - api-skeletons/zf-doctrine-audit 0.2.0 requires zendframework/zendframework ~2.4,<2.5 -> satisfiable by zendframework/zendframework[2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9] but these conflict with your requirements or minimum-stability.
    - api-skeletons/zf-doctrine-audit 0.1.0 requires zendframework/zendframework ~2.4,<2.5 -> satisfiable by zendframework/zendframework[2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove zendframework/zend-cache 2.5.3
    - api-skeletons/zf-doctrine-audit 2.0.0 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.1 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.2 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.3 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.4 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.5 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.6 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.7 requires doctrine/doctrine-orm-module ^1.1.5 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8].
    - api-skeletons/zf-doctrine-audit 2.0.8 requires doctrine/doctrine-orm-module ^1.1.5 || ^2.1 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5].
    - api-skeletons/zf-doctrine-audit 3.0.0 requires doctrine/doctrine-orm-module ^1.1.5 || ^2.1 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5].
    - api-skeletons/zf-doctrine-audit 3.0.1 requires doctrine/doctrine-orm-module ^1.1.5 || ^2.1 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5].
    - api-skeletons/zf-doctrine-audit 3.0.2 requires doctrine/doctrine-orm-module ^1.1.5 || ^2.1 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5].
    - api-skeletons/zf-doctrine-audit dev-master requires doctrine/doctrine-orm-module ^1.1.5 || ^2.1 -> satisfiable by doctrine/doctrine-orm-module[1.1.5, 1.1.6, 1.1.7, 1.1.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5].
    - doctrine/doctrine-orm-module 1.1.5 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0, 1.2.x-dev].
    - doctrine/doctrine-orm-module 1.1.6 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0, 1.2.x-dev].
    - doctrine/doctrine-orm-module 1.1.7 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0, 1.2.x-dev].
    - doctrine/doctrine-orm-module 1.1.8 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0, 1.2.x-dev].
    - doctrine/doctrine-orm-module 2.1.0 requires doctrine/doctrine-module ^2.1 -> satisfiable by doctrine/doctrine-module[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9].
    - doctrine/doctrine-orm-module 2.1.1 requires doctrine/doctrine-module ^2.1.3 -> satisfiable by doctrine/doctrine-module[2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9].
    - doctrine/doctrine-orm-module 2.1.2 requires doctrine/doctrine-module ^2.1.3 -> satisfiable by doctrine/doctrine-module[2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9].
    - doctrine/doctrine-orm-module 2.1.3 requires doctrine/doctrine-module ^2.1.3 -> satisfiable by doctrine/doctrine-module[2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9].
    - doctrine/doctrine-orm-module 2.1.4 requires doctrine/doctrine-module ^2.1.3 -> satisfiable by doctrine/doctrine-module[2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9].
    - doctrine/doctrine-orm-module 2.1.5 requires doctrine/doctrine-module ^2.1.3 -> satisfiable by doctrine/doctrine-module[2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9].
    - doctrine/doctrine-module 1.2.0 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 1.2.x-dev requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.0 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.1 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.2 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.3 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.4 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.5 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.6 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.7 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.8 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - doctrine/doctrine-module 2.1.9 requires zendframework/zend-cache ^2.7.1 -> satisfiable by zendframework/zend-cache[2.10.x-dev, 2.9.x-dev].
    - Can only install one of: zendframework/zend-cache[2.10.x-dev, 2.5.3].
    - Can only install one of: zendframework/zend-cache[2.9.x-dev, 2.5.3].
    - Installation request for zendframework/zend-cache 2.5.3 -> satisfiable by zendframework/zend-cache[2.5.3].
    - Installation request for api-skeletons/zf-doctrine-audit * -> satisfiable by api-skeletons/zf-doctrine-audit[0.1.0, 0.2.0, 0.3.0, 1, 1.0.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 3.0.0, 3.0.1, 3.0.2, dev-master].`

And here is my composer.json:

`{
    "name": "nhebi/mrss",
    "description": "Maximizing Resources for Student Success",
    "license": "proprietary",
    "keywords": [
        "education",
        "benchmarking"
    ],
    "homepage": "http://nccbp.org",
    "require": {
        "php": ">=7.1.0",
        "zendframework/zendframework": "2.5.*",
        "zendframework/zendservice-recaptcha": "2.0.*@dev",
        "zendframework/zend-cache": "2.5.3",
        "phly/phly-contact": "dev-master",
        "phing/phing": "2.*",
        "zf-commons/zfc-user": "*",
        "zf-commons/zfc-user-doctrine-orm": "*",
        "mtudor/zfc-user-impersonate": "*",
        "doctrine/doctrine-orm-module": "*",
        "doctrine/migrations": "*",
        "doctrine/dbal": "*",
        "doctrine/common": "*",
        "doctrine/cache": "*",
        "doctrine/annotations": "*",
        "doctrine/collections": "*",
        "doctrine/inflector": "1.1.*",
        "api-skeletons/zf-doctrine-audit": "*",
        "gedmo/doctrine-extensions": "2.4.*",
        "phpoffice/phpexcel": "1.8.*",
        "mwillbanks/zfc-twitter-bootstrap": "*",
        "bjyoungblood/bjy-authorize": "1.3.*",
        "goalio/goalio-mailservice": "1.0.1",
        "goalio/goalio-forgotpassword": "*",
        "goalio/goalio-forgotpassword-doctrine-orm": "*",
        "thesoftwarefarm/exprlib": "*",
        "rwoverdijk/assetmanager": "1.*",
        "zendframework/zend-developer-tools": "*",
        "fab1en/rocket-chat-rest-client": "dev-master",
        "mischiefcollective/colorjizz": "dev-master",
        "zendframework/zftool": "dev-master",
        "mikemix/zf2htmlpurifier": "~1.0",
        "breyndotechse/recaptcha2": "dev-master",
        "markrogoyski/math-php": "0.*",
        "maglnet/magl-markdown": "~1.1",
        "ext-json": "*",
        "sebastian/resource-operations": "1.0.0"
    },
    "require-dev": {
        "symfony/http-kernel": "2.*",
        "symfony/debug": "2.*",
        "symfony/http-foundation": "2.*",
        "symfony/filesystem": "2.*",
        "symfony/stopwatch": "2.*",
        "symfony/console": "2.*",
        "squizlabs/php_codesniffer": "2.*",
        "phpunit/phpunit": "*",

        "behat/behat": "*",
        "behat/mink": "*",
        "behat/mink-extension": "*",
        "behat/mink-goutte-driver": "*",
        "behat/mink-selenium2-driver": "*",
        "behat/mink-zombie-driver": "*",
        "phpmd/phpmd": "*",
        "psr/log": "1.0.0",
        "codeclimate/php-test-reporter": "dev-master"
    },
    "minimum-stability": "dev",
    "config": {
        "bin-dir": "bin/"
    }
}
`

**Comment by TomHAnderson** [comment]
Have you tried version 3.0.5?
https://github.com/API-Skeletons/zf-doctrine-audit/releases

**Comment by personman** [comment]
The latest version I see there is 3.0.2. But wouldn't anything in the 3.* series require me to upgrade ZF to version 3? Yesterday I created a fork, made a branch from release 1.0.1, and then changed composer.json to allow it to work with ZF 2.5.x. I've been able to get that to install, but when I try to run the console commands they are just throwing empty exceptions.

**Comment by TomHAnderson** [comment]
I'm sorry I can't help with this.  I'm not keen on backwards-supporting ZF < 3.
